export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_CURRENCIES_SUCCESS = 'LOAD_CURRENCIES_SUCCESS';
export const UPDATE_CURRENCY_AMOUNT_SUCCESS = 'UPDATE_CURRENCY_AMOUNT_SUCCESS';
export const CALCULATE_RETURN_SUCCESS = 'CALCULATE_RETURN_SUCCESS';
export const DISPLAY_ERROR_MESSAGE_AMOUNT= 'DISPLAY_ERROR_MESSAGE_AMOUNT';
